name: INSULATSCORE
main: InsulatorGMan\INSULATSCORE
api: [3.0.0]
version: 6.0.0
author: Grant-Stahr
description: Add fully customizable scoreboards to your server.

virions:
- ScoreFactory
- UpdateNotifier
- ConfigUpdater

permissions:
  sh.command.sh:
    default: false
    description: Allow players to use /scorehud command.
